In [ ]:
#DataFrames :- when we combine multiple Series Together it form DataFrames

In [2]:
import numpy as np
import pandas as pd

In [ ]:
Creating a DataFrames

In [19]:
data = {
    'Name':['Manisha','Sayali','Sanika','Sai'],
    'Age':[18,19,19,20],
    'Department':['CS','IT','ME','ENTC'],
    'Marks':[98,86,97,78]
}
df1 = pd.DataFrame(data)

In [24]:
data_list = [
    ['Manisha',18,'CS',98],
    ['Sayali',19,'IT',86],
    ['Sanika',19,'ME',97],
    ['Sai',20,'ENTC',88]
]
df2=pd.DataFrame(data_list)
columns=['Name','Age','Department','Marks']
df2=pd.DataFrame(data_list,columns=columns)

In [20]:
df2

         0   1     2   3
0  Manisha  18    CS  98
1   Sayali  19    IT  86
2   Sanika  19    ME  97
3      Sai  20  ENTC  88

In [21]:
df1

      Name  Age Department  Marks
0  Manisha   18         CS     98
1   Sayali   19         IT     86
2   Sanika   19         ME     97
3      Sai   20       ENTC     78

In [23]:
df1['Name']

0    Manisha
1     Sayali
2     Sanika
3        Sai
Name: Name, dtype: object

In [25]:
df2[["Name",'Marks']]

      Name  Marks
0  Manisha     98
1   Sayali     86
2   Sanika     97
3      Sai     88

In [ ]:
Creating a New Column

In [32]:
df2["Grade"]=["A","D","B","C"]

In [33]:
df2

      Name  Age Department  Marks Grade
0  Manisha   18         CS     98     A
1   Sayali   19         IT     86     D
2   Sanika   19         ME     97     B
3      Sai   20       ENTC     88     C

In [ ]:
Removing a Column

In [34]:
df2.drop("Grade",axis=1)

      Name  Age Department  Marks
0  Manisha   18         CS     98
1   Sayali   19         IT     86
2   Sanika   19         ME     97
3      Sai   20       ENTC     88

In [35]:
df2

      Name  Age Department  Marks Grade
0  Manisha   18         CS     98     A
1   Sayali   19         IT     86     D
2   Sanika   19         ME     97     B
3      Sai   20       ENTC     88     C

In [36]:
df2.drop("Grade",axis=1,inplace=True)

In [37]:
df2

      Name  Age Department  Marks
0  Manisha   18         CS     98
1   Sayali   19         IT     86
2   Sanika   19         ME     97
3      Sai   20       ENTC     88

In [38]:
df2.drop(0,axis=0)

     Name  Age Department  Marks
1  Sayali   19         IT     86
2  Sanika   19         ME     97
3     Sai   20       ENTC     88

In [ ]:
Selecting a Rows

In [39]:
df2.loc[0]

Name          Manisha
Age                18
Department         CS
Marks              98
Name: 0, dtype: object

In [41]:
df2.loc[[0,1]]

      Name  Age Department  Marks
0  Manisha   18         CS     98
1   Sayali   19         IT     86

In [42]:
df2.iloc[2]

Name          Sanika
Age               19
Department        ME
Marks             97
Name: 2, dtype: object

In [ ]:
Selecting subset of  rows and columns

In [43]:
df2.loc[[2,3]] [["Name","Age"]]

     Name  Age
2  Sanika   19
3     Sai   20

In [ ]:
Conditinal Selection

In [44]:
df2

      Name  Age Department  Marks
0  Manisha   18         CS     98
1   Sayali   19         IT     86
2   Sanika   19         ME     97
3      Sai   20       ENTC     88

In [45]:
#I want only see those people whose age is above 19
df2[df2["Age"]>19]

  Name  Age Department  Marks
3  Sai   20       ENTC     88

In [47]:
#I want only see those people whose age is above 18 and whose Department ME
df2[(df2["Age"]>18) & (df2["Department"]=='ME')]

     Name  Age Department  Marks
2  Sanika   19         ME     97