In [2]:
import numpy as np
import pandas as pd

Merging 2 data frames

In [13]:
# First DataFrame - Students
students = {
    "emp_id":[1,2,3,10,7],
    "Name": ["Manisha", "Sayali", "Sanika", "Sai", "Shreya"],
    "Marks": [85, 92, 89, 76, 88],
    "Age": [21, 22, 20, 19, 23]
}
pd.DataFrame(students)

   emp_id     Name  Marks  Age
0       1  Manisha     85   21
1       2   Sayali     92   22
2       3   Sanika     89   20
3      10      Sai     76   19
4       7   Shreya     88   23

In [12]:
courses = {
    "emp_id":[1,2,8,9,4],
    "Course": ["Manisha", "Sayali", "Sanika", "Sai", "Shreya"],
    "Duration_Months": [3, 4, 6, 8, 5],
    "Fees": [15000, 18000, 25000, 30000, 40000]
}
pd.DataFrame(courses)

   emp_id   Course  Duration_Months   Fees
0       1  Manisha                3  15000
1       2   Sayali                4  18000
2       8   Sanika                6  25000
3       9      Sai                8  30000
4       4   Shreya                5  40000

In [15]:
df_students = pd.DataFrame(students)

In [16]:
df_courses = pd.DataFrame(courses)

In [18]:
merged_df = pd.merge(df_students, df_courses, on="emp_id",how="inner")
merged_df

   emp_id     Name  Marks  Age   Course  Duration_Months   Fees
0       1  Manisha     85   21  Manisha                3  15000
1       2   Sayali     92   22   Sayali                4  18000

In [19]:
merged_df = pd.merge(df_students, df_courses, on="emp_id",how="outer")
merged_df

   emp_id     Name  Marks   Age   Course  Duration_Months     Fees
0       1  Manisha   85.0  21.0  Manisha              3.0  15000.0
1       2   Sayali   92.0  22.0   Sayali              4.0  18000.0
2       3   Sanika   89.0  20.0      NaN              NaN      NaN
3       4      NaN    NaN   NaN   Shreya              5.0  40000.0
4       7   Shreya   88.0  23.0      NaN              NaN      NaN
5       8      NaN    NaN   NaN   Sanika              6.0  25000.0
6       9      NaN    NaN   NaN      Sai              8.0  30000.0
7      10      Sai   76.0  19.0      NaN              NaN      NaN

In [20]:
merged_df = pd.merge(df_students, df_courses, on="emp_id",how="left")
merged_df

   emp_id     Name  Marks  Age   Course  Duration_Months     Fees
0       1  Manisha     85   21  Manisha              3.0  15000.0
1       2   Sayali     92   22   Sayali              4.0  18000.0
2       3   Sanika     89   20      NaN              NaN      NaN
3      10      Sai     76   19      NaN              NaN      NaN
4       7   Shreya     88   23      NaN              NaN      NaN

In [21]:
merged_df = pd.merge(df_students, df_courses, on="emp_id",how="right")
merged_df

   emp_id     Name  Marks   Age   Course  Duration_Months   Fees
0       1  Manisha   85.0  21.0  Manisha                3  15000
1       2   Sayali   92.0  22.0   Sayali                4  18000
2       8      NaN    NaN   NaN   Sanika                6  25000
3       9      NaN    NaN   NaN      Sai                8  30000
4       4      NaN    NaN   NaN   Shreya                5  40000

In [ ]:
Concatanation of 2 DataFrames

In [22]:
students_1 = {
    "emp_id": [1, 2, 3],
    "Name": ["Manisha", "Sayali", "Sanika"],
    "Marks": [85, 92, 89]
}
df1=pd.DataFrame(students_1)

In [24]:
df1

   emp_id     Name  Marks
0       1  Manisha     85
1       2   Sayali     92
2       3   Sanika     89

In [27]:
students_2 = {
    "emp_id": [4, 5, 6],
    "Name": ["Sai", "Shreya", "Shubhangi"],
    "Marks": [76, 88, 91]
}
df2=pd.DataFrame(students_2)

In [28]:
df2

   emp_id       Name  Marks
0       4        Sai     76
1       5     Shreya     88
2       6  Shubhangi     91

In [29]:
pd.concat([df1,df2])

   emp_id       Name  Marks
0       1    Manisha     85
1       2     Sayali     92
2       3     Sanika     89
0       4        Sai     76
1       5     Shreya     88
2       6  Shubhangi     91

In [30]:
pd.concat([df1,df2],axis=1) #On the basis of rows

   emp_id     Name  Marks  emp_id       Name  Marks
0       1  Manisha     85       4        Sai     76
1       2   Sayali     92       5     Shreya     88
2       3   Sanika     89       6  Shubhangi     91

In [31]:
pd.concat([df1,df2],axis=0) #On the basis of column

   emp_id       Name  Marks
0       1    Manisha     85
1       2     Sayali     92
2       3     Sanika     89
0       4        Sai     76
1       5     Shreya     88
2       6  Shubhangi     91

In [ ]:
Joining of 2 DataFrames

In [38]:
df1 = pd.DataFrame({
    "emp_id": [1, 2, 3, 4],
    "Name": ["Manisha", "Sayali", "Sanika", "Sai"],
    "Marks": [85, 92, 89, 76]
})

In [44]:
df1

   emp_id     Name  Marks
0       1  Manisha     85
1       2   Sayali     92
2       3   Sanika     89

In [45]:
df2 = pd.DataFrame({
    "emp_id": [1, 2, 4, 5],
    "Course": ["Python", "Java", "AI", "Data Science"],
    "Fees": [15000, 18000, 25000, 30000]
})

In [46]:
df2

   emp_id        Course   Fees
0       1        Python  15000
1       2          Java  18000
2       4            AI  25000
3       5  Data Science  30000

In [48]:
pd.merge(df1, df2, on="emp_id")

   emp_id     Name  Marks  Course   Fees
0       1  Manisha     85  Python  15000
1       2   Sayali     92    Java  18000

In [49]:
pd.merge(df1, df2, on="emp_id",how='outer')

   emp_id     Name  Marks        Course     Fees
0       1  Manisha   85.0        Python  15000.0
1       2   Sayali   92.0          Java  18000.0
2       3   Sanika   89.0           NaN      NaN
3       4      NaN    NaN            AI  25000.0
4       5      NaN    NaN  Data Science  30000.0