In [2]:
import numpy as np
import pandas as pd

In [ ]:
Pivot Table #A Pivot Table is used to summarize, organize, and analyze data in a table format.
#Pivot tables make large data easy to understand.

In [8]:

data = {
    "Name": ["Manisha", "Sayali", "Sanika", "Shreya", "Sai"],
    "City": ["Pune", "Mumbai", "Pune", "Nashik", "Mumbai"],
    "Marks": [8,7,9,7,1],
    "Grade": ["A", "B", "A+", "B", "A"],
    "Percentage":[89,90,91,77,87]
}

df = pd.DataFrame(data)

In [9]:
df

      Name    City  Marks Grade  Percentage
0  Manisha    Pune      8     A          89
1   Sayali  Mumbai      7     B          90
2   Sanika    Pune      9    A+          91
3   Shreya  Nashik      7     B          77
4      Sai  Mumbai      1     A          87

In [14]:
pivot1=pd.pivot_table(df,values='Marks',index='Grade',columns='Name')
pivot1

Name   Manisha  Sai  Sanika  Sayali  Shreya
Grade
A          8.0  1.0     NaN     NaN     NaN
A+         NaN  NaN     9.0     NaN     NaN
B          NaN  NaN     NaN     7.0     7.0

In [11]:
pd.pivot_table(df,values='Marks',index='Grade',columns='Name',aggfunc='median')

Name   Manisha  Sai  Sanika  Sayali  Shreya
Grade
A          8.0  1.0     NaN     NaN     NaN
A+         NaN  NaN     9.0     NaN     NaN
B          NaN  NaN     NaN     7.0     7.0

In [15]:
pivot2=pd.pivot_table(df,values=['Marks','Percentage'],index='Grade',columns='Name',aggfunc='median')
pivot2

        Marks                           Percentage
Name  Manisha  Sai Sanika Sayali Shreya    Manisha   Sai Sanika Sayali Shreya
Grade
A         8.0  1.0    NaN    NaN    NaN       89.0  87.0    NaN    NaN    NaN
A+        NaN  NaN    9.0    NaN    NaN        NaN   NaN   91.0    NaN    NaN
B         NaN  NaN    NaN    7.0    7.0        NaN   NaN    NaN   90.0   77.0

In [ ]:
Cross Tabs #crosstab() is used to calculate the frequency (count) between two or more columns.
#It creates a table showing how many times categories occur together.
#It is similar to a Pivot Table, but mainly used for counting data.

In [19]:
pd.crosstab(df['City'],['Name'])

col_0   Name
City
Mumbai     2
Nashik     1
Pune       2